<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Riftward.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Riftward.Platform/Riftward.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RiftHarness.Tests" />
  </ItemGroup>

</Project>
